@startuml
set namespaceSeparator ::

class "facade_wea::facade_wea.dart::WeatherApi" {
  -String _apiKey
  -String _baseUrl
  -String _cityName
  +Future<Map<String, dynamic>> getCurrentWeather()
}

class "facade_wea::facade_wea.dart::WeatherFacade" {
  -WeatherApi _weatherApi
  +Future<String> getCurrentTemperature()
  +Future<String> getCurrentDescription()
}

"facade_wea::facade_wea.dart::WeatherFacade" o-- "facade_wea::facade_wea.dart::WeatherApi"


@enduml